---

- name: Install epel-release
  package:
    name: "epel-release"
    state: present

# The with_items is required here to make
# sure epel-release is configured on the host
# before installing the python-pip package
- name: Install python-pip.
  package:
    name: "python-pip"
    state: present