- name: "Prepare auth material for Docker secure API"
  hosts: docker_swarm_manager
  become: yes
  roles:
    - role: docker_remote

- name: "Provision Docker Swarm Cluster"
  hosts: all
  become: yes
  roles:
    - role: docker_storage
    - role: atosatto.docker-swarm